name = "The Basics"
author = "imide"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d964bad2b2dfec8c8fba1672a8b2c0aa7f839a693942449291992e82cd555d6"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
