[light_sources]
	water_sensitive_check = true
	self = true
	block_entities = true
	entities = true

			[light_sources.settings.entities.minecraft]
				chicken = true
				bee = true
				arrow = true
				cow = true
				chest_minecart = true
				magma_cube = true
				pig = true
				skeleton = true
				iron_golem = true
				bat = true
				zombified_piglin = true
				rabbit = true
				cat = true
				zombie = true
				firework_rocket = true
				ender_pearl = true
				silverfish = true
				armor_stand = true
				drowned = true
				sheep = true
				fireball = true
				experience_orb = true
				player = true
				item = true
				turtle = true
				villager = true
				wolf = true
				skeleton_horse = true
				salmon = true
				zombie_villager = true
				ocelot = true
				item_frame = true
				horse = true
				minecart = true
				painting = true
				mooshroom = true
				cave_spider = true
				glow_squid = true
				cod = true
				witch = true
				squid = true
				snowball = true
				spider = true
				wither = true
				creeper = true
				lightning_bolt = true
				enderman = true
